[package]
name = "paradox-savedata"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_parser"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.0", features = ["extension-module"] }
nom = "7.1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"